syntax = "proto3";

package cupos.v1;

service Cupos {
  rpc ConsultarCurso(ConsultarCursoRequest) returns (Curso);
  rpc ListarCursos(ListarCursosRequest) returns (stream Curso);
  rpc OcuparCupo(ModificarCupoRequest) returns (Curso);
  rpc LiberarCupo(ModificarCupoRequest) returns (Curso);
}

message Curso {
  string id = 1;
  string nombre = 2;
  int32 cupos_totales = 3;
  int32 cupos_disponibles = 4;
}

message ConsultarCursoRequest { string curso_id = 1; }
message ListarCursosRequest {}
message ModificarCupoRequest { string curso_id = 1; }
