# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cupos.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'cupos.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x63upos.proto\x12\x08\x63upos.v1\"U\n\x05\x43urso\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06nombre\x18\x02 \x01(\t\x12\x15\n\rcupos_totales\x18\x03 \x01(\x05\x12\x19\n\x11\x63upos_disponibles\x18\x04 \x01(\x05\")\n\x15\x43onsultarCursoRequest\x12\x10\n\x08\x63urso_id\x18\x01 \x01(\t\"\x15\n\x13ListarCursosRequest\"(\n\x14ModificarCupoRequest\x12\x10\n\x08\x63urso_id\x18\x01 \x01(\t2\x8c\x02\n\x05\x43upos\x12\x42\n\x0e\x43onsultarCurso\x12\x1f.cupos.v1.ConsultarCursoRequest\x1a\x0f.cupos.v1.Curso\x12@\n\x0cListarCursos\x12\x1d.cupos.v1.ListarCursosRequest\x1a\x0f.cupos.v1.Curso0\x01\x12=\n\nOcuparCupo\x12\x1e.cupos.v1.ModificarCupoRequest\x1a\x0f.cupos.v1.Curso\x12>\n\x0bLiberarCupo\x12\x1e.cupos.v1.ModificarCupoRequest\x1a\x0f.cupos.v1.Cursob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cupos_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CURSO']._serialized_start=25
  _globals['_CURSO']._serialized_end=110
  _globals['_CONSULTARCURSOREQUEST']._serialized_start=112
  _globals['_CONSULTARCURSOREQUEST']._serialized_end=153
  _globals['_LISTARCURSOSREQUEST']._serialized_start=155
  _globals['_LISTARCURSOSREQUEST']._serialized_end=176
  _globals['_MODIFICARCUPOREQUEST']._serialized_start=178
  _globals['_MODIFICARCUPOREQUEST']._serialized_end=218
  _globals['_CUPOS']._serialized_start=221
  _globals['_CUPOS']._serialized_end=489
# @@protoc_insertion_point(module_scope)
