# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import cupos_pb2 as cupos__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in cupos_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CuposStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ConsultarCurso = channel.unary_unary(
                '/cupos.v1.Cupos/ConsultarCurso',
                request_serializer=cupos__pb2.ConsultarCursoRequest.SerializeToString,
                response_deserializer=cupos__pb2.Curso.FromString,
                _registered_method=True)
        self.ListarCursos = channel.unary_stream(
                '/cupos.v1.Cupos/ListarCursos',
                request_serializer=cupos__pb2.ListarCursosRequest.SerializeToString,
                response_deserializer=cupos__pb2.Curso.FromString,
                _registered_method=True)
        self.OcuparCupo = channel.unary_unary(
                '/cupos.v1.Cupos/OcuparCupo',
                request_serializer=cupos__pb2.ModificarCupoRequest.SerializeToString,
                response_deserializer=cupos__pb2.Curso.FromString,
                _registered_method=True)
        self.LiberarCupo = channel.unary_unary(
                '/cupos.v1.Cupos/LiberarCupo',
                request_serializer=cupos__pb2.ModificarCupoRequest.SerializeToString,
                response_deserializer=cupos__pb2.Curso.FromString,
                _registered_method=True)


class CuposServicer:
    """Missing associated documentation comment in .proto file."""

    def ConsultarCurso(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListarCursos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OcuparCupo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LiberarCupo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CuposServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ConsultarCurso': grpc.unary_unary_rpc_method_handler(
                    servicer.ConsultarCurso,
                    request_deserializer=cupos__pb2.ConsultarCursoRequest.FromString,
                    response_serializer=cupos__pb2.Curso.SerializeToString,
            ),
            'ListarCursos': grpc.unary_stream_rpc_method_handler(
                    servicer.ListarCursos,
                    request_deserializer=cupos__pb2.ListarCursosRequest.FromString,
                    response_serializer=cupos__pb2.Curso.SerializeToString,
            ),
            'OcuparCupo': grpc.unary_unary_rpc_method_handler(
                    servicer.OcuparCupo,
                    request_deserializer=cupos__pb2.ModificarCupoRequest.FromString,
                    response_serializer=cupos__pb2.Curso.SerializeToString,
            ),
            'LiberarCupo': grpc.unary_unary_rpc_method_handler(
                    servicer.LiberarCupo,
                    request_deserializer=cupos__pb2.ModificarCupoRequest.FromString,
                    response_serializer=cupos__pb2.Curso.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cupos.v1.Cupos', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cupos.v1.Cupos', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Cupos:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ConsultarCurso(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cupos.v1.Cupos/ConsultarCurso',
            cupos__pb2.ConsultarCursoRequest.SerializeToString,
            cupos__pb2.Curso.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListarCursos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/cupos.v1.Cupos/ListarCursos',
            cupos__pb2.ListarCursosRequest.SerializeToString,
            cupos__pb2.Curso.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OcuparCupo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cupos.v1.Cupos/OcuparCupo',
            cupos__pb2.ModificarCupoRequest.SerializeToString,
            cupos__pb2.Curso.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LiberarCupo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cupos.v1.Cupos/LiberarCupo',
            cupos__pb2.ModificarCupoRequest.SerializeToString,
            cupos__pb2.Curso.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

